//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pro_CodeGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pro_CodeGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Threading.Tasks;
        ///using Microsoft.AspNetCore.Http;
        ///using Microsoft.AspNetCore.Mvc;
        ///using Models.Models;
        ///using pro_API.Repositories;
        ///
        ///namespace pro_API.Controllers
        ///{
        ///    [Route(&quot;api/[controller]&quot;)]
        ///    [ApiController]
        ///    public class -Model-Controller : ControllerBase
        ///    {
        ///        private readonly I-Model-mentRepo -model-mentRepo;
        ///
        ///        public -Model-Controller(I-Model-mentRepo -model-mentRepo)
        ///        {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _Model_Controller {
            get {
                return ResourceManager.GetString("-Model-Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.EntityFrameworkCore;
        ///using Models.Models;
        ///using pro_API.Data;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Threading.Tasks;
        ///
        ///namespace pro_API.Repository
        ///{
        ///    public class -Model-Repository : I-Model-mentRepository
        ///    {
        ///        private readonly AppDbContext appDbContext;
        ///
        ///        public -Model-mentRepo(AppDbContext appDbContext)
        ///        {
        ///            this.appDbContext = appDbContext;
        ///        }
        ///        async Task&lt;IEnumerable&lt;-Model-&gt;&gt; I-M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _Model_Repository {
            get {
                return ResourceManager.GetString("_Model_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Models.Models;
        ///using System.Collections.Generic;
        ///using System.Threading.Tasks;
        ///
        ///namespace pro_API.Repository
        ///{
        ///    public interface I-Model-Repository
        ///    {
        ///        Task&lt;IEnumerable&lt;-Model-&gt;&gt; Search(string name);
        ///        Task&lt;IEnumerable&lt;-Model-&gt;&gt; Get-Model-s();
        ///        Task&lt;-Model-&gt; Get-Model-(int -model-Id);
        ///        Task&lt;-Model-&gt; Add-Model-(-Model- -model-);
        ///        Task&lt;-Model-&gt; Update-Model-(-Model- -model-);
        ///        Task&lt;-Model-&gt; Delete-Model-(int -model-Id);
        ///        
        ///        ///// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string I_Model_Repository {
            get {
                return ResourceManager.GetString("I-Model-Repository", resourceCulture);
            }
        }
    }
}
